// Desc: print haikus from Basho
exports.fn = function (helper, to, from, msg, store, cb, proto) {
  'use strict'
  var resp

  if (msg.match(/^\/help$|^help:$/)) {
    resp = "basho - looks for the phrase 'basho' anywhere in a line and returns a haiku from basho."
    cb(to, from, resp, proto)
    return
  }

  if (!store.phrases) {
    store.phrases = [
      'A autumn wind\nMore white\nThan the rocks in the rocky mountain.',
      'A caterpillar\nthis deep in fall\nstill not a butterfly',
      'A cold rain starting\nAnd no hat --\nSo?',
      'A cuckoo cries,\nand through a thicket of bamboo\nthe late moon shines',
      'A dragonfly, trying to –\noops, hang on to the upside\nof a blade of grass',
      'A green willow, \ndripping down into the mud, \nat low tide.  ',
      "A lightning gleam:\ninto darkness travels\na night heron's scream.",
      'A little girl under a peach tree,\nWhose blossoms fall into the entrails\nOf the earth.',
      'A lovely spring night\nsuddenly vanished while we\nviewed cherry blossoms',
      'A mountain pheasant cry \nfills me with fond longing for \nfather and mother',
      'A solitary\ncrow on a bare branch-\nautumn evening ',
      'A thicket of summer grass\nIs all that remains\nOf the dreams of ancient warriors.',
      'A weathered skeleton\nin windy fields of memory,\npiercing like a knife',
      'A wild sea-\nIn the distance over Sado\nThe Milky Way.',
      'All along this road\nnot a single soul – only\nautumn evening comes ',
      "All day in grey rain\nhollyhocks follow the sun's\ninvisible road",
      'All my friends\nviewing the moon –\nan ugly bunch',
      'All the day long- \nyet not long enough for the skylark,\nsinging, singing.',
      'All the fields hands\nenjoy a noontime nap after\nthe harvest moon',
      'All the rains of June\nit brings together, and it is swift --\nthe river Morgami.',
      "Along my journey\nthrough this transitory world,\nnew year's housecleaning ",
      'Along the roadside, \nblossoming wild roses \nin my horse’s mouth',
      'Along this way,\nno travellers.\nDusk in autumn.',
      'Among moon gazers\nat the ancient temple grounds\nnot one beautiful face ',
      'An ivy spray\nTrained up over the wall\nAnd a few bamboos\nInviting a tempest.',
      'As firmly cemented clam-shells\nFall apart in autumn,\nSo I must take to the road again,\nFarewell, my friends.',
      'At the ancient pond\na frog plunges into\nthe sound of water ',
      'Autumn approaches\nand the heart begins to dream\nof four-tatami rooms ',
      'Autumn full moon,\nthe tides slosh and foam\ncoming in',
      'Awake at night,\nThe lamp low,\nThe oil freezing.',
      'Awakened at midnight\nby the sound of the water jar\ncracking from the ice ',
      'Baby mice in their nest \nsqueak in response \nto the young sparrows',
      'Behind Ise Shrine,\nunseen, hidden by the fence,\nBuddha enters nirvana ',
      'Black Cloudbank broken\nScatters in the night...Now see\nMoon-lighted mountains!',
      'Breakfast enjoyed\nin the fine company of\nmorning glories ',
      "Buddha's Death Day \nfrom wrinkled praying hands \nthe rosaries' sound",
      'Bush clover in blossom waves\nWithout spilling\nA drop of dew.',
      'But for a woodpecker\ntapping at a post, no sound\nat all in the house ',
      'Butterfly -\nWings curve into\nWhite poppy.',
      'By a singular stroke\nOf luck, I saw a solitary hawk circling\nAbove the promontory of Irago.',
      'By the old temple, \npeach blossoms; \na man treading rice.',
      'Cedar umbrellas, off\nto Mount Yoshimo for\nthe cherry blossoms.',
      'Chilling autumn rains\ncurtain Mount Fuji, then make it\nmore beautiful to see ',
      'Cho tori-no\nShiranu hana ari\nAki no sora\nUnknown to birds and butterflies\nA flower blooms\nThe autumn sky',
      'Clouds come from time to time --\nand bring to men a chance to rest\nfrom looking at the moon.',
      'Clouds of cherry blossoms!\nIs that temple bell in Ueno\nor Asakusa? ',
      'Cold as it was\nWe felt secure sleeping together\nIn the same room.',
      'Cold white azalea - \nLone nun\nUnder thatched roof.',
      'Come out to view\nthe truth of flowers blooming\nin poverty ',
      'Crossing half the sky,\non my way to the capital,\nbig clouds promise snow ',
      'Crossing long fields, \nfrozen in its saddle, \nmy shadow creeps by',
      "Culture's beginnings:\nrice-planting songs from the heart\nof the country ",
      'Dark night - \nPlover crying \nFor its nest.',
      'Deep into autumn\nand this caterpillar\nstill not a butterfly',
      'Delight, then sorrow,\naboard the cormorant\nfishing boat ',
      'Do the tea-pickers also,\nhidden in the bushes,\nhear the hototogishu?',
      'Dying cricket,\nhow he sings out\nhis life!',
      'Eaten alive by \nlice and fleas -- now the horse \nbeside my pillow pees',
      'Even a wild boar\nWith all other things\nBlew in this storm.',
      'Even in Kyoto,\nhow I long for Kyoto\nwhen the cuckoo sings ',
      'Even that old horse \nis something to see this \nsnow-covered morning',
      'Even these long days\nare not nearly long enough\nfor the skylarks to sing ',
      'Exhausted, I sought\na country inn, but found\nwisteria in bloom ',
      'Farewell, my old fan.\nHaving scribbled on it,\nWhat could I do but tear it\nAt the end of summer?',
      'Firefly viewing -\nDrunken steersman,\nDrunken boat.',
      'First snow\nFalling\nOn the half-finished bridge.',
      'Flower \nunder harvest sun - stranger\nTo bird, butterfly.',
      'For those who proclaim \nthey’ve grown weary of children, \nthere are no flowers',
      'Fresh spring!\nThe world is only Nine days old - \nThese fields and mountains!',
      'Frog pond -- \nA leaf falls in\nWithout a sound',
      'From all directions\nWinds bring petals of cherry\nInto the grebe lake.',
      'From all these trees –\nin salads, soups, everywhere –\ncherry blossoms fall ',
      "From among the peach-trees\n'Blooming everywhere,' \nThe first cherry blossoms.",
      'From every direction\ncherry blossom petals blow\ninto Lake Biwa ',
      'Gray hairs being plucked,\nand from below my pillow\na cricket singing ',
      'Hailstones\nGlancing off the rocks\nAt Stony Pass.',
      'Heard, not seen,\nthe camellia poured rainwater\nwhen it leaned ',
      'Heated spring air\nIn tiny waves of an inch or two -\nAbove wintery grass.',
      "Hello! Light the fire!\nI'll bring inside \na lovely bright ball of snow",
      "How admirable,\nHe who thinks not, 'Life is fleeting,'\nWhen he sees the lightning!",
      'How many priests\nHow many morning glories\nHave perished under the pine\nEternal as law?',
      "How still it is!\nStinking into the stones,\nthe locusts' trill.",
      'How very noble!\nOne who finds no satori \nin the lightning-flash ',
      'How wild the sea is,\nand over Sado Island,\nthe River of Heaven',
      'Husking rice,\na child squints up\nto view the moon. ',
      "I didn't die!\nthe end of a journey\nis autumn nightfall",
      'I felt quite at home,\nAs if it were mine sleeping lazily\nIn this house of fresh air.',
      'I like to wash,\nthe dust of this world\nIn the droplets of dew.',
      "I would like to use\nthat scarecrow's tattered clothes\nin this midnight frost ",
      "I'm a wanderer\nso let that be my name –\nthe first winter rain ",
      'Ill on a journey,\nall about the dreary fields\nfly my broken dreams.',
      'In the bitter radish that\nbites into me, I feel the\nautumn wind',
      'In the moonlight a worm\nsilently\ndrills through a chestnut',
      'In this warm spring rain, \ntiny leaves are sprouting \nfrom the eggplant seed',
      'I’ll take these back\nfor the city slickers –\nsour chestnuts',
      'June clouds,\nAt ease on\nArashiyama Peak.',
      "Kannon's* tiled temple\nroof floats far away in clouds\nof cherry blossoms\n(Bodhisattva of Compassion)",
      "Kareeda ni\nkarasu no tomari keri\naki no kure\nOn dead branches \nCrows remain perched\nAt autumn's end.",
      "Kiso's chestnuts\nfor a person of the floating world\na souvenir",
      'Kochira muke\nWare mo sabishiki\nAki no kure\nWill you turn toward me?\nI am lonely too,\nThis autumn evening.',
      'Lead my pony\nacross this wide moor to where\nthe cuckoo sings ',
      "Lonely silence,\na single cicada's cry\nsinking into stone ",
      'Long conversations\nbeside blooming irises –\njoys of life on the road ',
      'Melon \nIn morning dew,\nmud-fresh.',
      "Mii Temple\nknocking on the gate for a wish\ntoday's moon",
      'Misty rain;\nToday is a happy day,\nAlthough Mt. Fuji is unseen.',
      'Mogami River, yanking\nThe burning sky\nInto the sea.',
      'Morning and evening\nSomeone waits at Matsushima!\nOne-sided love.',
      "Morning glory trailing --\nAll day the gate-\nbolt's fastened.",
      'My eyes following\nuntil the bird was lost at sea\nfound a small island',
      'My horse \nClip-clopping over the fields--Oh ho!\nI too am part of the picture!',
      'My way –\nno-one on the road\nand it’s autumn, getting dark',
      'New Year’s first snow -- ah -- \njust barely enough to tilt \nthe daffodil',
      'No blossoms and no moon,\nand he is drinking sake\nall alone!',
      'Not even a hat --\nand cold rain falling on me?\nTut-tut! Think of that!',
      'Now I see her face,\nthe old woman, abandoned,\nthe moon her only companion ',
      'O bush warblers! \nNow you’ve shit all over \nmy rice cake on the porch',
      'Octopus traps -\nsummer’s moonspun dreams,\nsoon ended. ',
      'Oh, these spring days!\nA nameless little mountain,\nwrapped in morning haze!',
      "On Buddha's birthday\na spotted fawn is born –\njust like that ",
      "On Buddha's deathday,\nwrinkled tough old hands pray –\nthe prayer beads' sound ",
      "On New Year's Day\neach thought a loneliness \nas winter dusk descends ",
      'On a journey,\nResting beneath the cherry blossoms,\nI feel myself to be in a Noh play.',
      'On the cow shed\nA hard winter rain; \nCock crowing.',
      'On the polished surface\nOf the divine glass,\nChaste with flowers of snow.',
      'On the white poppy, \na butterfly’s torn wing \nis a keepsake',
      'On this road \nwhere nobody else travels\nautumn nightfall',
      'Only half the way I came\nTo the ancient capital,\nAnd above my head\nClouds heavy with snow.',
      "Over skylark's song\nNoh cry \nOf Pheasant",
      'Over the ruins of a shrine\na chestnut tree\nstill lifts its candles',
      "Passing through the world\nIndeed this is just\nSogi's rain shelter.",
      'Petals of the mountain rose\nFall now and then,\nTo the sound of the waterfall?',
      'Polished and polished \nclean, in the holy mirror\nsnow flowers bloom ',
      'Scarecrow in the hillock\nPaddy field --\nHow unaware!  How useful!',
      'Searching storehouse eaves,\nrapt in plum blossom smells,\nthe mosquito hums ',
      "Seas slowly darken\nand the wild duck's plaintive cry\ngrows faintly white ",
      'Shake, oh grave!\nThe autumn wind\nIs the voice of my wailing.',
      'Shizukasa ya\nIwa ni shimi-iru\nSemi no koe\nCalm and serene\nThe sound of a cicada\nPenetrates the rock',
      'Should I hold them in my hand,\nThey will disappear\nIn the warmth of my tears,\nIcy strings of frost.',
      'Sick on my journey,\nonly my dreams will wander\nthese desolate moors',
      'Singing, planting rice,\nvillage songs more lovely\nthan famous city poems ',
      'Skylark on moor --\nSweet song\nOf non-attachment.',
      'Sleep on horseback,\nThe far moon in a continuing dream,\nSteam of roasting tea.',
      'Slender, so slender \nits stalk bends under dew -- \nlittle yellow flower',
      'Sparrow, spare\nThe horsefly\nDallying in flowers.',
      'Sparrows \nIn rape-field,\nBlossom-viewing.',
      'Sparrows in eves\nMice in ceiling -\nCelestial music.',
      'Spring air --\nWoven moon\nAnd plum scent.',
      "Spring departs.\nBirds cry\nFishes' eyes are filled with tears",
      'Spring rain \nconveyed under the trees\nin drops.',
      "Spring rain\nLeaking through the roof,\nDripping from the wasps' nest.",
      'Spring too, very soon!\nThey are setting the scene for it --\nplum tree and moon.',
      'Spring!\nA nameless hill\nin the haze.',
      'Stone Mountain\nwhiter than the stones \nautumn wind',
      'Summer grasses: \nall that remains of great soldiers’ \nimperial dreams',
      'Summer in the world;\nfloating on the waves \nof the lake.',
      'Summer moon -\nClapping hands, \nI herald dawn.',
      'Summer zashiki\nMake move and enter\nThe mountain and the garden.',
      'Taking a nap,\nFeet planted\nAgainst a cool wall.',
      'Temple bells die out.\nThe fragrant blossoms remain.\nA perfect evening!',
      'Tethered horse;\nsnow\nin both stirrups.',
      'That great blue oak\nindifferent to all blossoms\nappears more noble',
      'The Chestnut by the eaves\nIn magnificent bloom\nPasses unnoticed\nBy men of this world.',
      'The banana tree\nblown by winds pours raindrops\ninto the bucket ',
      'The bee emerging \nfrom deep within the peony \ndeparts reluctantly',
      'The beginning of autumn;\nThe sea and fields,\nAll one same green.',
      'The clouds come and go,\nproviding a rest for all\nthe moon viewers ',
      'The crescent lights\nThe misty ground.\nBuckwheat flowers.',
      "The dragonfly\nCan't quite land\nOn that blade of grass.",
      "The farmer's roadside\nhedge provided lunch for\nmy tired horse",
      'The first day of the year:\nthoughts come - and there is loneliness;\nthe autumn dusk is here.',
      'The first snow,\nJust enough to bend\nThe leaves of the daffodils.',
      'The first snow\nthe leaves of the daffodil\nbending together',
      'The leafless cherry,\nOld as a toothless woman,\nBlooms in flowers,\nMindful of its youth.',
      'The lightning flashes\nAnd slashing through the darkness,\nA night-heron’s screech.',
      'The lilies!\nThe stems, just as they are,\nthe flowers, just as they are.',
      'The moon about to appear,\nall present tonight\nwith their hands on their knees.',
      'The moon is the guide,\nCome this way to my house,\nSo says the host of a wayside inn.',
      'The morning glories\nbloom, securing the gate\nin the old fence ',
      'The oak tree stands\nnoble on the hill even in\ncherry blossom time',
      'The old pond: \na frog jumps in,- \nthe sound of water.',
      'The old pond;\nthe frog.\nPlop!',
      'The petals tremble \non the yellow mountain rose –\nroar of the rapids',
      'The pine tree of Shiogoshi\nTrickles all night long\nShiny drops of moonlight.',
      'The shallows –\na crane’s thighs splashed\nin cool waves',
      'The she cat - \nGrown thin\nFrom love and barley.',
      "The summer's grass!\nall that's left\nof ancient warriors' dreams.",
      "The sun's way:\nhollyhocks turn toward it\nthrough all the rains of May.",
      'The temple bell stops.\nBut the sound keeps coming\nout of the flowers.',
      'The usually hateful crow:\nhe, too -- this morning,\non the snow!',
      'The voices of plovers\nInvite me to stare into the darkness\nOf the Starlit Promontory.',
      'The warbler sings\namong new shoots of bamboo\nof coming old age ',
      'The wind from Mt. Fuji\nI put it on the fan.\nHere, the souvenir from Edo.',
      'The winds of fall\nare blowing, yet how green\nthe chestnut burr.',
      'The winter leeks\nHave been washed white --\nHow cold it is!',
      'The winter storm\nHid in the bamboo grove\nAnd quieted away.',
      'This bright harvest moon\nkeeps me walking all night long\naround the little pond ',
      'This first fallen snow\nis barely enough to bend\nthe jonquil leaves ',
      'This hot day swept away\ninto the sea by the\nMogami River ',
      'This ruined temple\nshould have its sad tale told only\nby a clam digger ',
      'Three months after we saw\nCherry blossoms together\nI came to see the glorious\nTwin trunks of the pine.',
      'Traveling this high\nmountain trail, delighted\nby violets ',
      'Tremble, oh my gravemound,\nin time my cries will be\nonly this autumn wind ',
      "Ugoku ha mo\nNaku osoroshiki\nNatsu kodachi \nEven leaves don't move\nAwesome is the\nSummer grove",
      'Under the image of Buddha\nAll these spring flowers\nSeem a little tiresome.',
      "Ungraciously, under\na great soldier's empty helmet,\na cricket sings ",
      'Unknowingly he guided us\nover pathless hills\nwith wisps of hay',
      'Unknown spring --\nPlum blossom\nBehind the mirror.',
      'Very brief:\nGleam of blossoms in the treetops\nOn a moonlit night.',
      "Wake, butterfly -\nIt's late, we've miles\nTo go together.",
      'Watching for snow,\nthe boozers’ faces –\na flash of lightning',
      "Water-drawing rites,\nicy sound of monks' getas\necho long and cold ",
      'Wet with morning dew\nand splotched with mud, the melon\nlooks especially cool ',
      'What luck!\nThe southern valley\nMake snow fragrant.',
      'Where cuckoo\nVanishes - \nAn island.',
      'Whore and monk, we sleep\nunder one roof together,\nmoon in a field of clover ',
      'Wild boars and all\nare blown along with it --\nstorm-wind of fall!',
      'Will you turn toward me?\nI am lonely, too,\nthis autumn evening.',
      'Winter downpour -\neven the monkey\nneeds a raincoat. ',
      'Winter rain --\nThe field stubble\nHas blackened.',
      'Winter seclusion –\nsitting propped against\nthe same worn post ',
      'Winter solitude--\nin a world of one color\nthe sound of wind.',
      'With a warbler for\na soul, it sleeps peacefully,\nthis mountain willow',
      'With dewdrops dripping,\nI wish somehow I could wash\nthis perishing world ',
      'With every gust of wind, \nthe butterfly changes its place \non the willow.',
      'With plum blossom scent,\nthis sudden sun emerges\nalong a mountain trail ',
      'With what kind of voice\nwould the spider cry\nin the autumn wind?',
      "Won't you come and see\nloneliness? Just one leaf\nfrom the kiri tree.",
      'Wrapping dumplings in\nbamboo leaves, with one finger\nshe tidies her hair ',
      'Yagate shinu\nKeshiki wa miezu\nSemi no koe\nCicadas singing --\nNo sign\nOf dying soon.',
      'Year’s end, all\ncorners of this\nfloating world, swept.',
      'Yellow rose petals\nThunder - \nA waterfall.',
      'a clear waterfall —\ninto the ripples\nfall green pine-needles',
      'a peasant’s child\nhusking rice, pauses\nto look at the moon',
      'a sick wild duck\nfalling down with the dark cold\nto sleep overnight',
      'a strange flower \nfor birds and butterflies\nthe autumn sky',
      'a terrible sound –\nthe gilded helmet’s \ntrapped cricket',
      'above the moor\nnot attached to anything\na skylark singing',
      'after the flowers\nall there is left for my haiku\nwisteria beans',
      'all night\nautumn winds being heard \nbehind the mountains',
      'all the more I wish to see\nin those blossoms at dawn\nthe face of a god',
      'along the mountain road\nsomehow it tugs at my heart—\na wild violet',
      'along this road\ngoing with no one\nautumn evening',
      'also green\nit should remain a thing\nthe pepper pod',
      'at Nara\nthe fragrance of chrysanthemums\nancient Buddhas',
      'at my poor hovel\nthere’s one thing I can offer —\nsmall mosquitoes',
      'autumn begins\nsea and sprouting rice fields\none green',
      'autumn colors\nwithout a pot\nof red-brown soup',
      'autumn coolness\nhand and hand paring away\neggplants -- cucumbers',
      'autumn deepens\nthe man next door\nhow is he doing?',
      'autumn nears\nmy heart is drawn \nto a four-mat room',
      'autumn night\nstriking and making it crumble\nour small talk',
      "autumn wind:\nas thickets in fields are \nFuwa's barriers",
      'autumn wind\nbroken with sadness\nhis mulberry stick',
      "autumn wind\nin Ise's shrine cemetery\neven more lonely",
      "autumn winds\nin the sliding door's opening \na sharp voice",
      "bagworm's place\nit seems to be inside\nthe cherry blossoms",
      'bagworms \nto hear their songs\ncome to my hut',
      'banana plant in autumn storm\nrain drips into tub\nhearing the night',
      'blowing stones\nflying from the volcano Asama\nautumn gale',
      "blue seas\nbreaking waves smell of rice wine \ntonight's moon",
      "borrowing sleep\nfrom the scarecrow's sleeves\nmidnight frost",
      'bright red\nthe pitiless sun\nautumn winds',
      'bush-clover flowers —\nthey sway but do not drop\ntheir beads of dew',
      "butt of the tree\nsee in the cut end\ntoday's moon",
      'butterflies flit\nin a field of sunlight\nthat is all',
      'butterflies flit…\nthat is all, amid the field\nof sunlight',
      'buying a measure box\nnow I feel differently\nabout moon-viewing',
      "chrysanthemum's scent\nin the garden a worn-out sandal \njust the sole",
      'chrysanthemums\nflowers blooming\nin the stones',
      'cloud-parting friend!\ntemporarily this wild goose\nmust go away',
      'cricket \nforgetting sounds with its cry\nby the fireplace',
      'departing autumn\nwith hands spread open\nchestnut burs',
      "don't imitate me\nwe are not two halves\nof a muskmelon",
      'drinking morning tea\nthe monk is peaceful\nthe chrysanthemum blooms',
      'ear of the pine tree\nmushroom on a strange tree\nwith a leaf stuck to it',
      'failing health\nchewing dried seaweed\nmy teeth grate on sand',
      'famous moon!\ncircling the pond all night\neven to the end',
      'flower of the harvest moon?\nit only looks that way\na cotton field',
      "for one touched by monkey cries\nhow is it when a child's abandoned\nin autumn winds",
      'fragrant orchid—\ninto a butterfly’s wings\nit breathes incense',
      'from this very day\nerase the inscription with dew\non the bamboo hat',
      'full autumn moon\nto my gate comes rising\ncrested tide',
      'grabbing at straws\nthe strength to bear\nour parting',
      'hair shaved in a moon-shape\nwith their hands on their knees\nin the early hours of night',
      'harvest moon\nnorthland weather\nuncertain skies',
      'higher than a skylark\nresting in the sky \non a mountain pass',
      'how piteous!\nbeneath the soldiers helmet\nchirps a cricket',
      'in blossoms\na horsefly plays… don’t eat it\nfriend-sparrow',
      'in my new clothing\ni feel so different, i must\nlook like someone else',
      'in the blossoms’ shade\nas in the noh drama\na traveller sleeps',
      "in the cow shed\nmosquito's voice darkens \nlingering heat",
      'in the world outside\nis it harvesting time?\nthe grass of my hut',
      'in your summer-room...\ngarden and mountain going too\nas we slowly walk',
      'it is spring!\na hill without a name\nin thin haze',
      'kono aki wa nande\ntoshiyoru kumo ni tori\nthis autumn \nas-for why grow old \ncloud to bird',
      'kono michi ya yuku hito nashi ni aki no kure\nthis road go \nperson nonexistent \nwith autumn’s evening',
      'looking carefully,\na shepherds purse is blooming\nunder the fence',
      "lotus pond\nas they are unplucked\nSouls' Festival",
      'low tide morning...\nthe willow skirts are tailed\nin stinking mud',
      'moonless night...\na powerful wind embraces\nthe ancient cedars',
      'not to think of yourself\nas someone who did not count --\nFestival of the Souls',
      'occasional clouds\none gets a rest\nfrom moon-viewing',
      'on a bare branch\na crow has settled\nautumn dusk',
      'on this mountain\ntell me of its sorrow\nwild-yam digger',
      'overhanging pine...\nadding its mite of needles\nto the waterfall',
      'people no longer live\nat the Fuwa Barrier\nin a house with wooden eaves',
      'petal by petal\nyellow mountain roses fall—\nsound of rapids',
      "rainy day\nthe world's autumn closes\nBoundary Town",
      'resting higher\nthan a lark in the sky\na mountain pass',
      'saying farewell to people\nfarewell being said to me brings\nautumn in Kiso',
      'secretly at night\na worm under the moon\nbores into a chestnut',
      'shaking the grave\nmy weeping voice\nautumn wind',
      'sleeping in the temple\nthe serious-looking face\nis moon-viewing',
      'so clear the sound\nechoes to the Big Dipper\nthe fulling block',
      "soon to die\nyet no sign of it\nin the cidada's chirpNothing in the cry \nof cicadas suggests they \nare about to die",
      "souls' festival\ntoday also there is smoke\nfrom the crematory",
      'speaking out\nmy lips are cold\nin autumn wind',
      "spiders have a cry?\nwell, what is chirping\nautumn's wind?",
      "stillness\npiercing the rocks\ncicada's shrill",
      'taken in my hand\nit will vanish in hot tears \nautumn frost',
      "temple bell\nalso sounds like it is\ncicada's voice",
      "the farmer's child \nrests from husking rice\nthen sees the moon",
      'the full moon \nseven story-songs of a woman\nturning towards the sea',
      'the moon so pure\na wandering monk carries it\nacross the sand',
      'the moon still is\nthough it seems far from home\nSuma in summer',
      'the moon:\nI wandered around the pond\nall night long',
      'the sea darkens —\nthe voices of the wild ducks\nare faintly white',
      'the setting moon\nthe thing that remains\nfour corners of his desk',
      "the village so old\nthere's not a single house \nwithout a persimmon tree",
      'the whole family\nall with white hair and canes\nvisiting graves',
      'thin from the Kiso trip\nand still not yet recovered\nthe late harvest moon',
      'this autumn\nas reason for growing old\na cloud and a bird',
      'this autumn\nwhy am I aging so?\nto the clouds a bird',
      "though a skylark sings\nbeating inside\nthe pheasant's sad cry",
      'though autumn winds blow\nit is still green\nbur of the chestnut',
      'to Kyoto\nstill half the sky to go—\nsnowy clouds',
      'turn this way!\nI too feel lonely\nlate in autumn',
      'under my tree-roof\nslanting lines of april rain\nseparate to drops',
      'very exciting\nyet after awhile so sad\ncormorant fishing',
      'viewing the moon\nno one at the party\nhas such a beautiful face',
      'walking on and on \neven through I fall down sick\nin fields of clover',
      'weathered bones\njust thinking of the wind\nit pierces my body',
      "where's the moon?\nas the temple bell is --\nsunk in the sea",
      'while growing thin\nwithout a reason\nthe chrysanthemum bud',
      "white chrysanthemum\ncatching in one's eye\nnary a speck of dust",
      'without turning\ninto a butterfly, autumn deepens \nfor the worm',
      'your hermitage\nthe moon and chrysanthemums \nplus an acre of rice fields'
    ]
  }

  if (msg.match(/^basho$|^bashō$/)) {
    resp = store.phrases[ helper.rand(store.phrases.length) ]
  }

  cb(to, from, resp, proto)
}
